### ISSUE TITLE
NPM Install Error 'library not found for -lbundle1.o"

### ISSUE THREAD

**Issue by maedi** [substack/watchify#129]
`npm install -g watchify`
Gave this error:

```javascript
> fsevents@0.3.4 install /usr/local/lib/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
ld: library not found for -lbundle1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.4
```
A quick Google brought up a similar issue:
https://github.com/lovell/sharp/issues/80

And my error was solved by that issues solution:
`xcode-select --install`

Maybe it's just me that didn't install XCode correctly. Just posting in case you'd like to fool proof the install instructions.

**Comment by zertosh** [comment]
Thanks! binary modules are pretty common in the node world, so you need a build toolchain. Everyone has a slightly different setup and everyone needs slightly different instructions for setting up the basics. So glad that stackoverflow exists :smile:
