### ISSUE TITLE
3.1, cannot find module '../'

### ISSUE THREAD

**Issue by caspervonb** [substack/watchify#183]
Just installed 3.1

```js
// test.js
console.log('test');
```

```sh
watchify test.js -o bundle.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/watchify/node_modules/browserify/bin/args.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by mattdesl** [comment]
due to https://github.com/substack/node-browserify/issues/1188

**Comment by mattdesl** [comment]
@caspervonb  
should be fixed now

**Comment by caspervonb** [comment]
Yep, resolved.
