### ISSUE TITLE
watchify fails when browserify's ignoreMissing options is used

### ISSUE THREAD

**Issue by edazdarevic** [substack/watchify#222]
Fatal error: path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:491:11)
    at OpenReq.process (/home/edin/projects/glu-vizwiz/node_modules/grunt-browserify/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:55:16)
    at OpenReq.Req (/home/edin/projects/glu-vizwiz/node_modules/grunt-browserify/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:126:8)
    at new OpenReq (/home/edin/projects/glu-vizwiz/node_modules/grunt-browserify/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:49:7)
    at Object.open (/home/edin/projects/glu-vizwiz/node_modules/grunt-browserify/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:41:3)
    at ReadStream.open (fs.js:1613:6)
    at new ReadStream (fs.js:1600:10)
    at Object.fs.createReadStream (fs.js:1554:10)
    at Deps.readFile (/home/edin/projects/glu-vizwiz/node_modules/grunt-browserify/node_modules/browserify/node_modules/module-deps/index.js:190:17)

**Comment by zertosh** [comment]
@edazdarevic Can you provide me with a repro case?

**Comment by cperryk** [comment]
I'm also seeing this error. It happens  when ignoreMissing is true, a script added to the bundle requires a module that's missing, and the bundle adds an additional module via [b.require](https://github.com/substack/node-browserify#brequirefile-opts). I've made a repo that reproduces it: https://github.com/cperryk/watchify_bug

To see the bug:
1. Open `mymodule.js` in a text editor.
1. In a terminal session, run `node builder.js`. This exports the bundle, then watches for changes.
1. Return to your text editor and save `mymodule.js`. This will trigger the watchify error in the terminal.

**Comment by zertosh** [comment]
@cperryk Ah something is def up. Thanks for the repro. I'm looking into it

**Comment by zertosh** [comment]
@cperryk I published the fix in module-deps@3.8.1 (a dependency of browserify). If you update browserify, it should work now.

**Comment by cperryk** [comment]
I'm finding that everything works fine now. Thank you!
