### ISSUE TITLE
Watchify is breaking .require() calls with the expose option

### ISSUE THREAD

**Issue by binarykitchen** [substack/watchify#74]
When the `bundler` is an instance of browserify, then this code works fine:

```js
    var bundler = browserify({
            entries:        ['main.js],
            insertGlobals:  false,
            debug:          !settings.PRODUCTION // for source maps
        })

    bundler.require('/home/xxx/var/local/tmp/client_settings.json', {
        expose: 'client_settings.json'
    })
```
but when I wrap this with watchify like that:

```js
    var bundler = watchify(browserify({
            entries:        ['main.js'],
            insertGlobals:  false,
            debug:          !settings.PRODUCTION // for source maps
        }), {
            watch: false
        })

    bundler.require('/home/xxx/var/local/tmp/client_settings.json', {
        expose: 'client_settings.json'
    })
```

then this error is thrown when bundling through a gulp task

```
TypeError: Cannot set property 'client_settings.json' of undefined
    at Browserify.<anonymous> (/home/xxx/node_modules/watchify/index.js:20:27)
    at Browserify.emit (events.js:95:17)
    at Transform._transform (/home/xxx/node_modules/browserify/index.js:475:14)
    at Transform._read (/home/xxx/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
...
```

**Comment by nervo** [comment]
Same kind of issue there

**Comment by zertosh** [comment]
I think this is related to https://github.com/substack/watchify/issues/72. I'm going to close this out and follow it there.
