### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by shawninder** [substack/watchify#87]
I'm trying to use the API in the simplest possible way, but it breaks on any call to `bundle()`. Of course I may be doing things wrong, but it's hard to tell because there is no example usage of the api (none that I can find anyways). I did look at the tests though and this looks as though it should word:
```
npm install watchify
npm install browserify
```
**index.js**
```
var browserify = require('browserify')
	, watchify = require('watchify')
	, b = browserify('./a.js', watchify.args)
	, w = watchify(b)

w.on('update', function () {
	w.bundle(function (err, src) {
		console.log('err', err)
		console.log('src', src)
	})
})

w.bundle(function (err, src) {
  console.log('err', err)
	console.log('src', src)
})
```
Running *index.js* produces the following error:
```
Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
    at Browserify.bundle (/Users/shawnfreyssonnet-inder/Work/gaston/node_modules/browserify/index.js:569:15)
    at Browserify.b.bundle (/Users/shawnfreyssonnet-inder/Work/gaston/node_modules/watchify/index.js:129:25)
    at Object.<anonymous> (/Users/shawnfreyssonnet-inder/Work/gaston/tests/perf/browserify/index.js:15:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
I also tried removing the functions in the calls to `bundle()` but that changes nothing

**Comment by zertosh** [comment]
This should work. Please open a new issue if you're still having this problem.

**Comment by shawninder** [comment]
Problem solved, thanks a lot!
